# Generated by Django 5.2.10 on 2026-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phno',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
