# Generated by Django 5.2.10 on 2026-01-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiro', '0002_user_phno_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_tname', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('phno', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('adhaar_no', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
