# Generated by Django 5.2.10 on 2026-01-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiro', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
