# Generated by Django 5.2.10 on 2026-01-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiro', '0004_rename_firs_tname_student_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
