# Generated by Django 5.2.10 on 2026-01-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiro', '0005_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='picfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('furl', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'picfile',
            },
        ),
    ]
