from django.urls import path
from . import views
urlpatterns =[
    path('test',views.test),
    path('test2',views.test2),
    path('index',views.index),
    path('aboutus',views.aboutus),
    path('contact',views.contact),
    path('register',views.register),
    path('login',views.login),
    path('login_check',views.login_check),
    path('log',views.log),
    path('logout',views.logout),
    path('add',views.add),
    path('sum',views.sum),
    path('eoo',views.eoo),
    path('evenorodd',views.evenorodd),
    path('fibonacci',views.fibonacci),
    path('fibo',views.fibo),
    path('calculator',views.calculator),
    path('insert',views.insert),
    path('ins',views.ins),
    path('show',views.show),
    path('student',views.student_input),
    path('student_entry',views.student_entry),
    path('show_student',views.show_student, name='student_list'),
    path('delta/<int:id>',views.delta),
    path('edit/<int:id>',views.edit),
    path('upd/<int:id>',views.upd, name='user_update'),
    path('del/<int:id>',views.sdel, name='student_delete'),
    path('update/<int:id>',views.update, name='student_update'),
    path('ed/<int:id>',views.ed, name='student_edit'),
    path('search',views.search),
    path('ser',views.ser),
    path('upload',views.upload, name='upload_page'),
    path('picfile',views.pfile),
    path('show_upload',views.show_upload, name='show_upload'),
    path('download/<int:file_id>',views.download_file, name='download_file'),
    path('weather_view',views.weather_view),
    path('send_email',views.send_email),
]